#!/bin/bash

BIN_DIR=`cd "$( dirname "$0" )"; pwd`

pushd $BIN_DIR > /dev/null

DEF_CLASS_PATH_FILE=.dep-class-path
if [ ! -f $DEF_CLASS_PATH_FILE ];
then
	mvn dependency:build-classpath | grep -ve "\[" > $DEF_CLASS_PATH_FILE
fi

java -cp target/Replay-0.1-SNAPSHOT.jar:`cat $DEF_CLASS_PATH_FILE` Replay "${@:2}"

popd > /dev/null

CUR_DATETIME=$2
HOSTNAME=`hostname`

if [ "$HOSTNAME" != "$1" ]; then
	scp -rp /mnt/multidc-data/pbdp/twitter/replay-log/$CUR_DATETIME/$HOSTNAME mdc-s70:/mnt/multidc-data/pbdp/twitter/replay-log/$CUR_DATETIME
fi
