#!/bin/bash

function less_output {
	prefix=$1
	args=$2
	rm -f $prefix-all
	echo "# "$args >> $prefix-all
	for f in $prefix/*
	do
		echo "["`basename $f`"]" >> $prefix-all
		cat $f >> $prefix-all
		echo "" >> $prefix-all
	done
	less $prefix-all
}

ARGS=$@
BIN_DIR=`cd "$( dirname "$0" )"; pwd`
CUR_DATETIME=`date +'%y%m%d-%H%M%S'`
OUT_DIR=/mnt/multidc-data/pbdp/twitter/replay-log/$CUR_DATETIME/stdout

mkdir -p $OUT_DIR
pssh -h $BIN_DIR/hosts --option="ForwardAgent yes" -t 0 -o $OUT_DIR "$BIN_DIR/_replay `hostname` $CUR_DATETIME $ARGS 2>&1 "

less_output $OUT_DIR "$ARGS"
