#!/bin/bash

function less_output {
	prefix=$1
	rm -f $prefix-all
	for f in $prefix/*
	do
		echo "["$f"]" >> $prefix-all
		cat $f >> $prefix-all
		echo "" >> $prefix-all
	done
	less -r $prefix-all
}

BIN_DIR=`cd "$( dirname "$0" )"; pwd`
ERR_DIR=/tmp/pssh-err
OUT_DIR=/tmp/pssh-out

echo "stopping ..."
rm -rf $ERR_DIR
rm -rf $OUT_DIR
pssh -h $BIN_DIR/hosts --option="ForwardAgent yes" -o $OUT_DIR -e $ERR_DIR $BIN_DIR/_stop-clean
less_output $ERR_DIR
less_output $OUT_DIR
echo

echo "starting ..."
pssh -h $BIN_DIR/hosts --option="ForwardAgent yes" -o $OUT_DIR -e $ERR_DIR -t 100 ~/work/cassandra/bin/cassandra
less_output $ERR_DIR
less_output $OUT_DIR
