#!/bin/bash

function less_output {
	prefix=$1
	rm -f $prefix-all
	for f in $prefix/*
	do
		echo "["$f"]" >> $prefix-all
		cat $f >> $prefix-all
		echo "" >> $prefix-all
	done
	less -r $prefix-all
}

if [ -z "$1" ]
then
	echo "Usage: "$0" remote_cmd"
	exit 1
fi

BIN_DIR=`cd "$( dirname "$0" )"; pwd`
ERR_DIR=/tmp/pssh-err
OUT_DIR=/tmp/pssh-out

rm -rf $ERR_DIR
rm -rf $OUT_DIR

pssh -h $BIN_DIR/host-list --option="ForwardAgent yes" -o $OUT_DIR -e $ERR_DIR $@

less_output $ERR_DIR
less_output $OUT_DIR
