#!/bin/bash

function less_output {
	prefix=$1
	\rm $prefix-all
	for f in $prefix/*
	do
		echo "["$f"]" >> $prefix-all
		cat $f >> $prefix-all
		echo "" >> $prefix-all
	done
	less -r $prefix-all
}

if [ -z "$1" ]
then
	echo "Usage: "$0" remote_cmd"
	exit 1
fi

BIN_DIR=`cd "$( dirname "$0" )"; pwd`

rm -rf $BIN_DIR/err
rm -rf $BIN_DIR/out

pssh -h $BIN_DIR/host-list --option="ForwardAgent yes" -o $BIN_DIR/out -e $BIN_DIR/err $@

less_output $BIN_DIR"/err"
less_output $BIN_DIR"/out"
